In [162]:
import numpy as np
import matplotlib.pyplot as plt

A[o<sup>y</sup>, o<sup>x</sup>, s<sup>y</sup>, s<sup>x</sup>] = p(o|s)

In [163]:
A = np.zeros((4, 4, 4, 4))

A[0, 0, 0, 0] = 0.5
A[0, 1, 0, 0] = 0.25
A[1, 0, 0, 0] = 0.25

A[1, 0, 1, 0] = 0.5
A[0, 0, 1, 0] = 0.5/3
A[1, 1, 1, 0] = 0.5/3
A[2, 0, 1, 0] = 0.5/3

A[2, 0, 2, 0] = 0.5
A[1, 0, 2, 0] = 0.5/3
A[2, 1, 2, 0] = 0.5/3
A[3, 0, 2, 0] = 0.5/3

A[3, 0, 3, 0] = 0.5
A[2, 0, 3, 0] = 0.25
A[3, 1, 3, 0] = 0.25

A[0, 1, 0, 1] = 0.5
A[0, 0, 0, 1] = 0.5/3
A[1, 1, 0, 1] = 0.5/3
A[0, 2, 0, 1] = 0.5/3

A[1, 1, 1, 1] = 0.5
A[0, 1, 1, 1] = 0.125
A[1, 0, 1, 1] = 0.125
A[2, 1, 1, 1] = 0.125
A[1, 2, 1, 1] = 0.125

A[2, 1, 2, 1] = 0.5
A[1, 1, 2, 1] = 0.125
A[2, 0, 2, 1] = 0.125
A[3, 1, 2, 1] = 0.125
A[2, 2, 2, 1] = 0.125

A[3, 1, 3, 1] = 0.5
A[2, 1, 3, 1] = 0.5/3
A[3, 0, 3, 1] = 0.5/3
A[3, 2, 3, 1] = 0.5/3

A[0, 2, 0, 2] = 0.5
A[0, 1, 0, 2] = 0.5/3
A[1, 2, 0, 2] = 0.5/3
A[0, 3, 0, 2] = 0.5/3

A[1, 2, 1, 2] = 0.5
A[0, 2, 1, 2] = 0.125
A[1, 1, 1, 2] = 0.125
A[2, 2, 1, 2] = 0.125
A[1, 3, 1, 2] = 0.125

A[2, 2, 2, 2] = 0.5
A[1, 2, 2, 2] = 0.125
A[2, 1, 2, 2] = 0.125
A[3, 2, 2, 2] = 0.125
A[2, 3, 2, 2] = 0.125

A[3, 2, 3, 2] = 0.5
A[2, 2, 3, 2] = 0.5/3
A[3, 1, 3, 2] = 0.5/3
A[3, 3, 3, 2] = 0.5/3

A[0, 3, 0, 3] = 0.5
A[0, 2, 0, 3] = 0.25
A[1, 3, 0, 3] = 0.25

A[1, 3, 1, 3] = 0.5
A[0, 3, 1, 3] = 0.5/3
A[1, 2, 1, 3] = 0.5/3
A[2, 3, 1, 3] = 0.5/3

A[2, 3, 2, 3] = 0.5
A[1, 3, 2, 3] = 0.5/3
A[2, 2, 2, 3] = 0.5/3
A[3, 3, 2, 3] = 0.5/3

A[3, 3, 3, 3] = 0.5
A[2, 3, 3, 3] = 0.25
A[3, 2, 3, 3] = 0.25

B[s<sup>y</sup><sub>t+1</sub>, s<sup>x</sup><sub>t+1</sub>, s<sup>y</sup><sub>t</sub>, s<sup>x</sup><sub>t</sub>, a<sub>t</sub>] = p(s<sub>t+1</sub>|s<sub>t</sub>, π)&emsp;(a $\in$ {0(='up'), 1(='right'), 2(='down'), 3(='left')})

In [164]:
B = np.zeros((4, 4, 4, 4, 4))

B[0, 0, 0, 0, 0] = 1
B[0, 1, 0, 0, 1] = 1
B[1, 0, 0, 0, 2] = 1
B[0, 0, 0, 0, 3] = 1

B[0, 0, 1, 0, 0] = 1
B[1, 1, 1, 0, 1] = 1
B[2, 0, 1, 0, 2] = 1
B[1, 0, 1, 0, 3] = 1

B[1, 0, 2, 0, 0] = 1
B[2, 1, 2, 0, 1] = 1
B[3, 0, 2, 0, 2] = 1
B[2, 0, 2, 0, 3] = 1

B[2, 0, 3, 0, 0] = 1
B[3, 1, 3, 0, 1] = 1
B[3, 0, 3, 0, 2] = 1
B[3, 0, 3, 0, 3] = 1

B[0, 1, 0, 1, 0] = 1
B[0, 2, 0, 1, 1] = 1
B[1, 1, 0, 1, 2] = 1
B[0, 0, 0, 1, 3] = 1

B[0, 1, 1, 1, 0] = 1
B[1, 2, 1, 1, 1] = 1
B[2, 1, 1, 1, 2] = 1
B[1, 0, 1, 1, 3] = 1

B[1, 1, 2, 1, 0] = 1
B[2, 2, 2, 1, 1] = 1
B[3, 1, 2, 1, 2] = 1
B[2, 0, 2, 1, 3] = 1

B[2, 1, 3, 1, 0] = 1
B[3, 2, 3, 1, 1] = 1
B[3, 1, 3, 1, 2] = 1
B[3, 0, 3, 1, 3] = 1

B[0, 2, 0, 2, 0] = 1
B[0, 3, 0, 2, 1] = 1
B[1, 2, 0, 2, 2] = 1
B[0, 1, 0, 2, 3] = 1

B[0, 2, 1, 2, 0] = 1
B[1, 3, 1, 2, 1] = 1
B[2, 2, 1, 2, 2] = 1
B[1, 1, 1, 2, 3] = 1

B[1, 2, 2, 2, 0] = 1
B[2, 3, 2, 2, 1] = 1
B[3, 2, 2, 2, 2] = 1
B[2, 1, 2, 2, 3] = 1

B[2, 2, 3, 2, 0] = 1
B[3, 3, 3, 2, 1] = 1
B[3, 2, 3, 2, 2] = 1
B[3, 1, 3, 2, 3] = 1

B[0, 3, 0, 3, 0] = 1
B[0, 3, 0, 3, 1] = 1
B[1, 3, 0, 3, 2] = 1
B[0, 2, 0, 3, 3] = 1

B[0, 3, 1, 3, 0] = 1
B[1, 3, 1, 3, 1] = 1
B[2, 3, 1, 3, 2] = 1
B[1, 2, 1, 3, 3] = 1

B[1, 3, 2, 3, 0] = 1
B[2, 3, 2, 3, 1] = 1
B[3, 3, 2, 3, 2] = 1
B[2, 2, 2, 3, 3] = 1

B[2, 3, 3, 3, 0] = 1
B[3, 3, 3, 3, 1] = 1
B[3, 3, 3, 3, 2] = 1
B[3, 2, 3, 3, 3] = 1

C[o<sup>y</sup>, o<sup>x</sup>, t] = p(R=1|o<sub>t</sub>)

In [165]:
C = np.ones((4, 4, 3)) / 16

C[:, :, 2] = np.zeros((4, 4))
C[2, 1, 2] = 1

D[s<sup>y</sup>, s<sup>x</sup>] = p(s)

In [180]:
D = np.zeros((4, 4))

D[3, 0] = 1

E[π] = p(π)&emsp;(π $\in$ {0(='Policy 1), 1(='Policy 2)})

In [167]:
E = np.zeros(2)

E[0] = 1/2
E[1] = 1/2

f[π, t] = a

In [181]:
f = np.zeros((2, 2), dtype=int)

f[0, 0] = 0
f[0, 1] = 0

f[1, 0] = 1
f[1, 1] = 0

In [182]:
# helper functions

def actionB2policyB(actionB, f, t, N_policies):
    policyB = np.zeros((4, 4, 4, 4, N_policies))

    for pi in range(N_policies):
        a = f[pi, t]
        policyB[:, :, :, :, pi] = actionB[:, :, :, :, a]

    return policyB
    
def safelog(x):
    return np.log(x + 1e-9)

def softmax(x):
    x_new = np.zeros((4, 4, x.shape[-1]))
    for i in range(x.shape[-1]):
        stabilized = x[:, :, i] - np.max(x[:, :, i])
        exp_x = np.exp(stabilized)
        x_new[:, :, i] = exp_x / np.sum(exp_x)
    return x_new

def sample(prob):
    prob_flat = prob.ravel()
    sampled_index_prob_flat = np.random.choice(a=np.arange(len(prob_flat)), size=1, p=prob_flat)[0]
    (row_index, column_index) = np.unravel_index(sampled_index_prob_flat, prob.shape)
    return (row_index, column_index)


In [183]:
def infer_meanfield(observables, A, B, C, D, E, f, REP):
    T = C.shape[2]
    t = len(observables)
    N_policies = len(E)

    q_hidden = np.ones((T, 4, 4, N_policies)) / 16
    q_obs = np.ones((T - t, 4, 4, N_policies)) / 16
    q_policy = np.ones(N_policies) / N_policies

    for rep in range(REP):
        for k in range(T):
            if k == 0:
                if k < t:
                    obs = (observables[k, 0], observables[k, 1])
                    past = safelog(D)[:, :, None]
                    present = safelog(A[obs[0], obs[1]])[:, :, None]
                    future = np.einsum('ijk,ijmnk->mnk', q_hidden[k + 1], safelog(actionB2policyB(B, f, k, N_policies)))
                    
                    q_hidden[k] = softmax(past + present + future)
                else:
                    past = safelog(D)[:, :, None]
                    present = np.einsum('ijk,ijmn->mnk', q_obs[k], safelog(A * C[:, :, k, None, None]))
                    future = np.einsum('ijk,ijmnk->mnk', q_hidden[k + 1], safelog(actionB2policyB(B, f, k, N_policies)))
                    
                    q_hidden[k] = softmax(past + present + future)
                                                 
                    q_obs[k] = softmax(np.einsum('mnp,ijmn->ijp', q_hidden[k], safelog(A * C[:, :, k, None, None])))
            elif k == T - 1:
                if k < t:
                    obs = (observables[k, 0], observables[k, 1])
                    past = np.einsum('ijk,mnijk->mnk', q_hidden[k - 1], safelog(actionB2policyB(B, f, k - 1, N_policies)))
                    present = safelog(A[obs[0], obs[1]])[:, :, None]
                    
                    q_hidden[k] = softmax(past + present)
                else:
                    past = np.einsum('ijk,mnijk->mnk', q_hidden[k - 1], safelog(actionB2policyB(B, f, k - 1, N_policies)))
                    present = np.einsum('ijk,ijmn->mnk', q_obs[k - t], safelog(A * C[:, :, k, None, None]))
                    
                    q_hidden[k] = softmax(past + present)
                    
                    q_obs[k - t] = softmax(np.einsum('mnp,ijmn->ijp', q_hidden[k], safelog(A * C[:, :, k, None, None])))
            else:
                if k < t:
                    obs = (observables[k, 0], observables[k, 1])
                    past = np.einsum('ijk,mnijk->mnk', q_hidden[k - 1], safelog(actionB2policyB(B, f, k - 1, N_policies)))
                    present = safelog(A[obs[0], obs[1]])[:, :, None]
                    future = np.einsum('ijk,ijmnk->mnk', q_hidden[k + 1], safelog(actionB2policyB(B, f, k, N_policies)))
                    
                    q_hidden[k] = softmax(future + present + past)
                else:
                    past = np.einsum('ijk,mnijk->mnk', q_hidden[k - 1], safelog(actionB2policyB(B, f, k - 1, N_policies)))
                    present = np.einsum('ijk,ijmn->mnk', q_obs[k - t], safelog(A * C[:, :, k, None, None]))
                    future = np.einsum('ijk,ijmnk->mnk', q_hidden[k + 1], safelog(actionB2policyB(B, f, k, N_policies)))
                    
                    q_hidden[k] = softmax(future + present + past)
                    
                    q_obs[k - t] = softmax(np.einsum('mnp,ijmn->ijp', q_hidden[k], safelog(A * C[:, :, k, None, None])))

    F = np.zeros(2)
    F -= np.einsum('ijp, ij -> p', q_hidden[0], safelog(D))
    for k in range(T):
        q_s_k = q_hidden[k]
        F += np.einsum('ijp, ijp -> p', q_s_k, safelog(q_s_k))
        if k > 0:
            B_policy_k = actionB2policyB(B, f, k-1, N_policies)
            q_s_k_minus_1 = q_hidden[k-1]
            q_s_k = q_hidden[k]
            F -= np.einsum('abp, ijp, abijp -> p', q_s_k, q_s_k_minus_1, safelog(B_policy_k))
        if k < t:
            o_y_k, o_x_k = observables[k]
            ln_A_k = safelog(A[o_y_k, o_x_k, :, :])
            F -= np.einsum('ijp, ij -> p', q_hidden[k], ln_A_k)
        else:
            q_o_k = q_obs[k - t]
            F += np.einsum('mnp, mnp -> p', q_o_k, safelog(q_o_k))
            F -= np.einsum('ijp, mnp, mnij -> p', q_hidden[k], q_obs[k - t], safelog(A))
            ln_C_k = safelog(C[:, :, k])
            F -= np.einsum('mnp, mn -> p', q_obs[k - t], ln_C_k)
    q_policy = (E * np.exp(-F)) / np.sum(E * np.exp(-F))
    
    return q_hidden, q_obs, q_policy
                

In [184]:
q_hidden, q_obs, q_policy = infer_meanfield(observables=np.array([(3, 0)]), A=A, B=B, C=C, D=D, E=E, f=f, REP=10)

np.set_printoptions(precision=3, suppress=True)

print('q(s_k):')
#             [k, s_y, s_x, π]
print(q_hidden[0,   :,   :, 0])
print()

print('q(o_k):')
#          [k, s_y, s_x, π]
print(q_obs[0,   :,   :, 0])
print()

print('q(π)')
#             [π]
print(q_policy[:])

q(s_k):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]

q(o_k):
[[0.    0.    0.    0.   ]
 [0.167 0.    0.    0.   ]
 [0.5   0.167 0.    0.   ]
 [0.167 0.    0.    0.   ]]

q(π)
[0. 1.]
