In [2]:
import numpy as np
import scipy.special as sp
from agent_parameters import A, B, C, D, U
from utils import optimize_q_s, safelog

In [3]:
epsilon = 0.1
alpha = np.ones((16, 8)) * epsilon
alpha[0, 0] = 10
alpha[0, 1] = 10
alpha[1, 0] = 10
alpha[1, 1] = 10
alpha[4, 2] = 1
alpha[5, 3] = 1
alpha[8, 4] = 1
alpha[9, 5] = 1
alpha[12, 6] = 1
alpha[13, 7] = 1

In [4]:
alpha

array([[10. , 10. ,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [10. , 10. ,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  1. ,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  1. ,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  1. ,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  1. ,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  1. ,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  1. ],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1]])

In [5]:
np.exp(sp.digamma(alpha[0,:]) - sp.digamma(np.sum(alpha, axis=0)))

array([4.54711594e-01, 4.54711594e-01, 1.47110510e-05, 1.47110510e-05,
       1.47110510e-05, 1.47110510e-05, 1.47110510e-05, 1.47110510e-05])

In [6]:
np.sum(alpha, axis=0)

array([21.4, 21.4,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

In [7]:
alpha / np.sum(alpha, axis=0)

array([[0.46728972, 0.46728972, 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.46728972, 0.46728972, 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.4       , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.4       , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.04      , 0.4       ,
        0.04      , 0.04    

In [8]:
sp.digamma(alpha + 1)

array([[ 2.35175259,  2.35175259, -0.42375494, -0.42375494, -0.42375494,
        -0.42375494, -0.42375494, -0.42375494],
       [ 2.35175259,  2.35175259, -0.42375494, -0.42375494, -0.42375494,
        -0.42375494, -0.42375494, -0.42375494],
       [-0.42375494, -0.42375494, -0.42375494, -0.42375494, -0.42375494,
        -0.42375494, -0.42375494, -0.42375494],
       [-0.42375494, -0.42375494, -0.42375494, -0.42375494, -0.42375494,
        -0.42375494, -0.42375494, -0.42375494],
       [-0.42375494, -0.42375494,  0.42278434, -0.42375494, -0.42375494,
        -0.42375494, -0.42375494, -0.42375494],
       [-0.42375494, -0.42375494, -0.42375494,  0.42278434, -0.42375494,
        -0.42375494, -0.42375494, -0.42375494],
       [-0.42375494, -0.42375494, -0.42375494, -0.42375494, -0.42375494,
        -0.42375494, -0.42375494, -0.42375494],
       [-0.42375494, -0.42375494, -0.42375494, -0.42375494, -0.42375494,
        -0.42375494, -0.42375494, -0.42375494],
       [-0.42375494, -0.42375494

In [9]:
sp.digamma(np.sum(alpha, axis=0) + 1)

array([3.08657348, 3.08657348, 1.10315664, 1.10315664, 1.10315664,
       1.10315664, 1.10315664, 1.10315664])

In [10]:
sp.digamma(alpha + 1) - sp.digamma(np.sum(alpha, axis=0) + 1)

array([[-0.73482089, -0.73482089, -1.52691158, -1.52691158, -1.52691158,
        -1.52691158, -1.52691158, -1.52691158],
       [-0.73482089, -0.73482089, -1.52691158, -1.52691158, -1.52691158,
        -1.52691158, -1.52691158, -1.52691158],
       [-3.51032842, -3.51032842, -1.52691158, -1.52691158, -1.52691158,
        -1.52691158, -1.52691158, -1.52691158],
       [-3.51032842, -3.51032842, -1.52691158, -1.52691158, -1.52691158,
        -1.52691158, -1.52691158, -1.52691158],
       [-3.51032842, -3.51032842, -0.68037231, -1.52691158, -1.52691158,
        -1.52691158, -1.52691158, -1.52691158],
       [-3.51032842, -3.51032842, -1.52691158, -0.68037231, -1.52691158,
        -1.52691158, -1.52691158, -1.52691158],
       [-3.51032842, -3.51032842, -1.52691158, -1.52691158, -1.52691158,
        -1.52691158, -1.52691158, -1.52691158],
       [-3.51032842, -3.51032842, -1.52691158, -1.52691158, -1.52691158,
        -1.52691158, -1.52691158, -1.52691158],
       [-3.51032842, -3.51032842

In [11]:
alpha / np.sum(alpha, axis=0) * (sp.digamma(alpha + 1) - sp.digamma(np.sum(alpha, axis=0) + 1))

array([[-0.34337425, -0.34337425, -0.06107646, -0.06107646, -0.06107646,
        -0.06107646, -0.06107646, -0.06107646],
       [-0.34337425, -0.34337425, -0.06107646, -0.06107646, -0.06107646,
        -0.06107646, -0.06107646, -0.06107646],
       [-0.0164034 , -0.0164034 , -0.06107646, -0.06107646, -0.06107646,
        -0.06107646, -0.06107646, -0.06107646],
       [-0.0164034 , -0.0164034 , -0.06107646, -0.06107646, -0.06107646,
        -0.06107646, -0.06107646, -0.06107646],
       [-0.0164034 , -0.0164034 , -0.27214892, -0.06107646, -0.06107646,
        -0.06107646, -0.06107646, -0.06107646],
       [-0.0164034 , -0.0164034 , -0.06107646, -0.27214892, -0.06107646,
        -0.06107646, -0.06107646, -0.06107646],
       [-0.0164034 , -0.0164034 , -0.06107646, -0.06107646, -0.06107646,
        -0.06107646, -0.06107646, -0.06107646],
       [-0.0164034 , -0.0164034 , -0.06107646, -0.06107646, -0.06107646,
        -0.06107646, -0.06107646, -0.06107646],
       [-0.0164034 , -0.0164034 

In [12]:
np.sum(alpha / np.sum(alpha, axis=0) * (sp.digamma(alpha + 1) - sp.digamma(np.sum(alpha, axis=0) + 1)), axis=0)

array([-0.91639615, -0.91639615, -1.18829587, -1.18829587, -1.18829587,
       -1.18829587, -1.18829587, -1.18829587])

In [13]:
np.sum(self.alpha / np.sum(self.alpha, axis=0) * (safelog(self.C) - safelog(self.observation_beliefs[k])), axis=0)

NameError: name 'self' is not defined

In [14]:
C

array([0.0262484 , 0.0262484 , 0.19395087, 0.00355233, 0.0262484 ,
       0.0262484 , 0.19395087, 0.00355233, 0.0262484 , 0.0262484 ,
       0.19395087, 0.00355233, 0.0262484 , 0.0262484 , 0.19395087,
       0.00355233])

In [ ]:
#alpha / np.sum(alpha, axis=0) * C
np.einsum('ij,i->ij', alpha / np.sum(alpha, axis=0), C).shape

(16, 8)

In [ ]:
alpha / np.sum(alpha, axis=0)

array([[0.46728972, 0.46728972, 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.46728972, 0.46728972, 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.4       , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.4       , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      ],
       [0.0046729 , 0.0046729 , 0.04      , 0.04      , 0.4       ,
        0.04      , 0.04    

In [19]:
number_actions = 4
tupel_laenge = 2

# Erstellt ein Gitter basierend auf den Dimensionen (4, 4, 4) und formt es direkt um
kombinationen_array = np.indices((number_actions,) * tupel_laenge).reshape(tupel_laenge, -1).T

print(kombinationen_array)

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


In [20]:
np.zeros(2).size

2

In [24]:
np.eye(4)[3]

array([0., 0., 0., 1.])