In [1]:
import numpy as np
import pandas as pd
from world import World

number_simulations = 1
time_horizon = 3
observations = np.zeros((number_simulations, time_horizon))

world = World(time_horizon)
alpha_init = np.zeros((16, 8))
alpha_init[...] = world.agent.alpha
#print(alpha_init)
#print(alpha_init / np.sum(alpha_init, axis=0))

In [2]:
def highlight_cells(data):
    styles = pd.DataFrame('', index=data.index, columns=data.columns)

    # Welche Zeilen/Spalten markiert werden sollen
    ziel_zeilen = [1, 3]  # Index 1 und 3 (2. und 4. Zeile)
    ziel_spalten = [2]    # Index 2 (3. Spalte)
    
    # --- DER ENTSCHEIDENDE UNTERSCHIED ---
    # Beide Listen werden gleichzeitig in iloc eingesetzt.
    # Das markiert nur noch die Zellen (1, 2) und (3, 2).
    styles.iloc[4, 2] = 'background-color: yellow'
    styles.iloc[5, 3] = 'background-color: yellow'
    styles.iloc[10, 4] = 'background-color: yellow'
    styles.iloc[14, 7] = 'background-color: yellow'
    styles.loc
        
    return styles

In [3]:
for _ in range(number_simulations): 
    world.run()
    observation = world.get_observations()

    print("State beliefs:")
    print(world.agent.state_beliefs)
    print("Observation beliefs:")
    print(world.agent.observation_beliefs)
    #print(observation)
    world.agent.learn_observation_likelihood()
    world.agent.reset()
    world.environment.reset()


    #print(world.agent.alpha / np.sum(world.agent.alpha, axis=0))

# DataFrame erstellen
df = pd.DataFrame(world.agent.alpha - alpha_init)

# 1. Spalten (oberste Zeile) durch Wörter ersetzen
neue_spaltennamen = ['O_RL', 'O_RR', 'C_RL', 'C_RR', 'L_RL', 'L_RR', 'R_RL', 'R_RR']
df.columns = neue_spaltennamen  # <--- HIER df statt data verwenden!

# 2. Zeilen (linke Spalte) durch Wörter ersetzen
neue_zeilennamen = [
    'O_CL', 'O_CR', 'O_RW', 'O_NR', 
    'C_CL', 'C_CR', 'C_RW', 'C_NR',
    'L_CL', 'L_CR', 'L_RW', 'L_NR',
    'R_CL', 'R_CR', 'R_RW', 'R_NR'
]
df.index = neue_zeilennamen  # <--- HIER df statt data verwenden!

# 3. Styling anwenden
styled_df = df.style.apply(highlight_cells, axis=None)

# Ausgabe im Notebook
styled_df

#print(world.agent.alpha)

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
[1.798e+308 1.798e+308 1.798e+308 1.798e+308 1.798e+308 1.798e+308 1.798e+308 1.798e+308]
[[0]
 [1]
 [2]
 [3]]
[1.798e+308 1.798e+308 1.798e+308 1.798e+308]


ValueError: cannot reshape array of size 0 into shape (0,newaxis)